name: Update neurocontainers

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  upload_containers_simg:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
    - uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name : Check if singularity container files exist in nectar cloud and build & upload if not there
      run: |
        /bin/bash .github/workflows/upload_to_zenodo.sh ${{ secrets.ZENODO_TOKEN }}