name: Update neurocontainers

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  upload_containers_simg:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
    - uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name : Check if singularity container files exist in nectar cloud and build & upload if not there
      run: |
        IMAGE_HOME=/home/runner
        IMAGENAME_BUILDDATE=dicomtools_1.0.0_20250204
        echo "[DEBUG] ${IMAGENAME_BUILDDATE}.simg exists in temporary cache on nectar cloud"
        curl --output "$IMAGE_HOME/${IMAGENAME_BUILDDATE}.simg" "https://object-store.rc.nectar.org.au/v1/AUTH_dead991e1fa847e3afcca2d3a7041f5d/neurodesk/temporary-builds-new/${IMAGENAME_BUILDDATE}.simg"
        echo "Upload container $IMAGE_HOME/${IMAGENAME_BUILDDATE}.simg to Zenodo"
        echo $(find $IMAGE_HOME/${IMAGENAME_BUILDDATE}.simg)
        export DOI_URL=$(python3 .github/workflows/publish-doi.py --container_filepath="$IMAGE_HOME/${IMAGENAME_BUILDDATE}.simg" --container_name=${IMAGENAME_BUILDDATE} --token=${{ secrets.ZENODO_TOKEN }})