name: Update neurocontainers

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/update-neurocontainers.yml'
      - 'neurodesk/apps.json'
      - 'neurodesk/write_log.py'

jobs:
  upload_containers_simg:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
    - uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name : Check if singularity container files exist in nectar cloud and build & upload if not there
      run: |
        /bin/bash .github/workflows/upload_containers_simg.sh ${{ secrets.ZENODO_TOKEN }}
    - name: Auto commit changes to applist.json
      uses: stefanzweifel/git-auto-commit-action@v4
      id: auto-commit-action
    - name: "Run if changes found to applist.json"
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      run: |
          curl -X POST https://api.github.com/repos/NeuroDesk/neurodesk.github.io/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "NeuroDesk/neurocommand applist.json update"}'